
const biologia2014uem = [
  {
    id: 'biologia2014uem1',
    text: 'A Taxonomia é a ciência que classifica os seres vivos. Qual dos cientistas abaixo mencionado é considerado o pai da Taxonomia?',
    answers: ['Darwin', 'Teofrasto', 'Aristóteles', 'Lineu', 'Charles'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 1,
    year: 2014
  },
  {
    id: 'biologia2014uem2',
    text: 'A classificação taxonómica que agrupa os seres vivos de acordo com o grau de parentesco entre eles é denominada de:',
    answers: ['Classificação evolutiva', 'Classificação prática', 'Classificação natural', 'Classificação racional', 'Classificação artificial'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 2,
    year: 2014
  },
  {
    id: 'biologia2014uem6',
    text: 'Considere os seguintes grupos vegetais: I – Briófitas; II – Gimnospermas; III – Angiospermas; IV –Pteridófitas. Assinale a alternativa correcta.',
    answers: ['Os quatro grupos são considerados plantas criptogâmicas', 'Os quatro grupos são considerados plantas fanerogâmicas', 'I e IV são considerados plantas criptogâmicas e II e III plantas fanerogâmicas', 'I e II são considerados plantas criptogâmicas e III e IV plantas fanerogâmicas', 'I, II e IV são considerados plantas criptogâmicas e III plantas fanerogâmicas'],
    correct: 2,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 6,
    year: 2014
  },
  {
    id: 'biologia2014uem7',
    text: 'Qual das características abaixo não é de uma Dicotiledônea?',
    answers: ['Sementes com dois cotilédones', 'Flores pentâmeras ou tetrâmeras', 'Folhas reticulinérveas', 'Caules com feixes vasculares dispersos', 'Sistema radicular pivotante'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 7,
    year: 2014
  },
  {
    id: 'biologia2014uem14',
    text: 'A membrana plasmática, apesar de ser invisível ao microscópio óptico, está presente:',
    answers: ['Em todas as células, seja ela procariótica ou eucariótica', 'Apenas nas células animais', 'Apenas nas células vegetais', 'Apenas nas células dos eucariontes', 'Apenas nas células dos procariontes'],
    correct: 0,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 14,
    year: 2014
  },
  {
    id: 'biologia2014uem16',
    text: 'O comportamento de hemácias e células vegetais, quando colocadas em meios hipotónicos, é diferente em virtude da:',
    answers: ['Diferença de funcionamento da membrana plasmática', 'Existência de vacúolos nas células vegetais', 'Existência de parede celulósica nas células vegetais', 'Porosidade da membrana celulósica', 'Inexistência de núcleo das hemácias'],
    correct: 2,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 16,
    year: 2014
  },
  {
    id: 'biologia2014uem17',
    text: 'São exemplos de células anucleadas:',
    answers: ['Célula parenquimática e célula muscular', 'Elemento de tubo crivado e hemácia de mamíferos', 'Hemácia de mamíferos e célula albuminosa', 'Elemento de vaso e macrófago', 'Vírus e hemácia de mamíferos'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 17,
    year: 2014
  },
  {
    id: 'biologia2014uem18',
    text: 'Nas células dos eucariontes autotróficos, as enzimas que actuam no processo fotossintético estão presentes:',
    answers: ['Nas invaginações da membrana plasmática', 'No interior das mitocôndrias', 'Dispersas no citoplasm fundamental', 'No interior dos cloroplastos', 'Na solução do vacúolo'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 18,
    year: 2014
  },
  {
    id: 'biologia2014uem19',
    text: 'Células de certos organismos possuem organelas que produzem ATP e os utilizam na síntese de substâncias orgânicas a partir de dioxido de carbono. Essas organelas são:',
    answers: ['Mitocôndrias', 'Lisossomas', 'Complexo de Golgi', 'Nucléolo', 'Cloroplastos'],
    correct: 4,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 19,
    year: 2014
  },
  {
    id: 'biologia2014uem20',
    text: 'Qual das funções abaixo não é do Retículo Endoplasmático?',
    answers: ['Produção de lípidos', 'Desintoxicação celular', 'Transporte de proteínas', 'Armazenamento de substâncias', 'Formação dos lisossomas'],
    correct: 4,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 20,
    year: 2014
  },
  {
    id: 'biologia2014uem28',
    text: 'O câmbio e o felogênio são duas formações vegetais constituídas por tecido:',
    answers: ['Meristemático de crescimento', 'Meristemático, de crescimento em comprimento, existente na raiz', 'Diferenciado, de crescimento, existente no caule e raiz', 'Diferenciado para condução, existente nas angiospermas', 'Diferenciado para promover absorção de água, existente nas raízes'],
    correct: 0,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 28,
    year: 2014
  },
  {
    id: 'biologia2014uem30',
    text: 'Num organismo, células musculares diferem das células nervosas principalmente por:',
    answers: ['Possuirem genes diferentes', 'Expressarem genes diferentes', 'Possuirem ribossomos diferentes', 'Utilizarem código genético diferente', 'Possuirem cromossomos diferentes'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 30,
    year: 2014
  },
  {
    id: 'biologia2014uem31',
    text: 'Para exercer as suas funções de reabsorção, as células epiteliais dos tubulos renais possuem:',
    answers: ['Vilosidades e muitas; mitocôndrias', 'Superficie lisa e poucas mitocôndrias', 'Vilosidades e poucas; mitocôndrias', 'Grandes vacuolos', 'Superfície lisa e muitas mitocôndrias'],
    correct: 4,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 31,
    year: 2014
  },
  {
    id: 'biologia2014uem32',
    text: 'Tripsina, pepsina e ptialina são enzimas digestivas produzidas respectivamente:',
    answers: ['Fígado, pâncreas e estômago', 'Pâncreas, estômago e glândulas salivares', 'Vilosidades e poucas; mitocôndrias', 'Pâncreas, glândulas salivares e estômago', 'Fígado, estômago e pâncreas'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 32,
    year: 2014
  },
  {
    id: 'biologia2014uem33',
    text: 'A maior parte do gás carbônico eliminado pelas células no seu metabolismo, é transportado no sangue:',
    answers: ['Combinado com a hemoglobina', 'Pelas hemácias', 'Na forma de ião bicarbonato dissolvido no plasma', 'Combinado com ião hidrogénio', 'Pelos leucócitos'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 33,
    year: 2014
  },
  {
    id: 'biologia2014uem35',
    text: 'O facto de que os neurônios não se reproduzirem nao pode ser generalizado para outras células, explicando-se corretamente, neste caso, porque:',
    answers: ['As células eucarióticas não se reproduzem', 'Quanto mais diferenciada for uma célula, menor será sua capacidade reprodutiva', 'Somente as células gâmicas são capazes de reprodução', 'As células lábeis são dotadas de alta capacidade de reprodução', 'Células alongadas nunca se reproduzem. (Junqueira & Carneiro, 2000)'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 35,
    year: 2014
  },
  {
    id: 'biologia2014uem36',
    text: 'No aparelho circulatório as trocas gasosas entre o sangue e os tecidos ocorrem ao nível de:',
    answers: ['Veias', 'Capilares', 'Vasos linfáticos', 'Artérias', 'Alvéolos'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 36,
    year: 2014
  },
  {
    id: 'biologia2014uem37',
    text: 'Sobre a reprodução humana, todas as afirmações abaixo mencionadas estão correctas excepto:',
    answers: ['A fecundação ocorre no útero', 'A espermatogênese ocorre nos testículos', 'A placenta é responsável pela respiração e nutrição do embrião', 'Na ovulação, rompe-se a parede do ovário e o ovócito é libertado na trompa de Falópio', 'A clivagem da célula-ovo origina células denominadas blastômeros'],
    correct: 0,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 37,
    year: 2014
  },
  {
    id: 'biologia2014uem38',
    text: 'A tuberculose é um grave problema de saúde no mundo, principlamente em áreas menos desenvolvidas como Moçambique. Qual é o principal agente causador da tuberculose no Homem?',
    answers: ['Escherichia coli', 'Vírus(bacilo de Koch)', 'Bactérias e Virus', 'Mycobacterium tuberculosis(Bacilo de Koch)', 'Bactérias e fungos'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 38,
    year: 2014
  },
  {
    id: 'biologia2014uem39',
    text: 'As vitaminas são substâncias orgânicas muito importates, indespensáveis à vida.A deficiência da vitamina D no organismo Humano tem como consequência:',
    answers: ['Inchaço e sangue nas gengivas', 'Distúrbios nervosos, fadiga e fraqueza', 'Inflamação da pele, ossos fracos e deformados', 'Osssos fracos e cegueira nocturna', 'Ossos fracos e raquitismo em recém-nascidos'],
    correct: 4,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 39,
    year: 2014
  },
  {
    id: 'biologia2014uem40',
    text: 'A fase menstrual marca o início do ciclo uterino e tem a duração média de 5 dias.Durante esta fase o ovário lança para o sangue as seguintes hormonas:',
    answers: ['Estrogénio e progesterona', 'Tiroxina e adrenalina', 'Progesterona e adrenalina', 'Estrogénio e tiroxina', 'Progesterona e tiroxina'],
    correct: 0,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 40,
    year: 2014
  },
  {
    id: 'biologia2014uem41',
    text: 'As aves precisam ter, para voar, uma eficiente coor denação motora.Considerando a proporção relativa dos componentes do encéfalo, as aves possuem, em relação a outros vertebrados, um maior desenvolvimento da seguinte estrutura encefálica:',
    answers: ['Bulbo', 'Cerebelo', 'Hipotálamo', 'Lobo frontal', 'Todos eles'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 41,
    year: 2014
  },
  {
    id: 'biologia2014uem42',
    text: 'A minhoca apresenta respiração(I) e circulação(II).Para completar correctamente essa frase, I e II devem ser substituídos, respectivamente por:',
    answers: ['Cutânea e aberta', 'Cutânea e fechada', 'Branquial e aberta', 'Branquial e fechada', 'Traquela e fechada'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 42,
    year: 2014
  },
  {
    id: 'biologia2014uem43',
    text: 'Qual das hormonas abaixo eleva a concentração de cálcio no sangue e em que gladula é essa hormana produzida?',
    answers: ['Calcitonina, tiróide', 'Calcitonina, paratiróide ', 'Paratohormona. tiróide', 'Paratohormona.paratiróide', 'Glucagona, insulina'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 43,
    year: 2014
  },
  {
    id: 'biologia2014uem44',
    text: 'Qual das classes do filo Arthropoda não possui tubos de Malpighi como orgãos excretores ?',
    answers: ['Insecta', 'Arachnida', 'Crustacea', 'Diplopoda', 'Chilopoda'],
    correct: 2,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 44,
    year: 2014
  },
  {
    id: 'biologia2014uem52',
    text: 'A fotossíntese ocorre em duas grandes etapas, que envolvem várias reações químicas.Assinale a alternativa que indica onde ocorre respectivamente a fase escura e a fase luminosa.',
    answers: ['Nos tilacóides e nas lamelas', 'Na membrana interna e nas lamelas', 'Nas lamelas e no estroma', 'No estroma e nos tilacóides', 'Na membrana interna e nos tilacóides'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 52,
    year: 2014
  },
  {
    id: 'biologia2014uem53',
    text: 'A gutação é o processo de libertação de água sob forma líquida feita pelas plantas, e ocorre quando:',
    answers: ['A pressão radicular é muito baixa', 'A pressão radicular é muito alta', 'Crustacea', 'Os diâmetro dos vasos conductores aumenta', 'O diâmetro dos vasos conductores diminui'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 53,
    year: 2014
  },
  {
    id: 'biologia2014uem54',
    text: 'Trocas gasosas entre as folhas e o meio ambiente; eliminação de água na forma líquida(gutação) e trocas gasosas nos caules, são fenómenos que ocorrem em diferentes vegetais.Eles são possiveis devido a presença de, respectivamente:',
    answers: ['Estomas, hidatódios e traqueídeos', 'Tricomas, lenticelas e hidatódiosArachnida', 'Estomas, hidatódios e lenticelas', 'Lenticelas, traqueídeos e acúleos', 'Vasos crivados, hidatódios e traqueídeos'],
    correct: 2,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 54,
    year: 2014
  },
  {
    id: 'biologia2014uem55',
    text: 'Durante o movimento fotoativo de abertura dos estomas, não se observa nas células guardas:',
    answers: ['Aumento da taxa de fotossíntese', 'Aumento no consumo de Co2 pelos cloroplastos', 'Variação do pH', 'Transformação de amido em glucose', 'Diminuição do turgor celular'],
    correct: 4,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 55,
    year: 2014
  },
  {
    id: 'biologia2014uem58',
    text: 'A energia imediata que supre o processo de contração muscular é derivada de ligações ricas em energia proveniente de:',
    answers: ['Adenosina trifosfato', 'Ácido pirúvico', 'Acilmercaptanas', 'Creatina fosfato', 'Adenosina difosfato'],
    correct: 0,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 58,
    year: 2014
  },
  {
    id: 'biologia2014uem59',
    text: 'São orgãos homólogos:',
    answers: ['Barbatanas de peixes e parápodes de poliquetas', 'Barbatanas anteriores de uma baleia e asas de morcego', 'Brânquias de camarão e brânquias de peixes', 'Barbatanas peitorais de peixes e braços de polvo', 'Asas de aves e asas de insectos'],
    correct: 1,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 59,
    year: 2014
  },
  {
    id: 'biologia2014uem60',
    text: 'O único anexo embrionário presente nos embriões dos anfíbios é:',
    answers: ['Alantóide', 'Âmnio', 'Córnio', 'Saco vetelínico', 'Placenta'],
    correct: 3,
    subject: 4,
    level: 11,
    institution: 0,
    nr: 60,
    year: 2014
  },
];

module.exports = biologia2014uem;