const geografia2014uem = [
  {
    id: 'geografia2014uem1',
    text: 'Vidal de La Blache (1845-1918), figura incontornável da Geografia, é representante da seguinte corrente geográfica:',
    answers: ['Determinista', 'Corológica', 'Nova Geografia', 'Possibilista', 'Radical'],
    correct: 3,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 1,
    year: 2014
  },
  {
    id: 'geografia2014uem2',
    text: 'De modo a comunicar os resultados do seu trabalho, os geógrafos usam muito:',
    answers: ['Pinturas', 'Mapas', 'Gráficos', 'Textos', 'Réguas'],
    correct: 1,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 2,
    year: 2014
  },
  {
    id: 'geografia2014uem3',
    text: 'Alfred Wegener foi autor da Teoria(de):',
    answers: ['Placas tectónicas', 'Explicativa do esfriamento da Terra', 'Perturbações vulcânicas e tectónicas', 'Estrutura externa da Terra', 'Deriva dos continentes'],
    correct: 4,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 3,
    year: 2014
  },
  {
    id: 'geografia2014uem4',
    text: 'O determinismo geográfico foi uma corrente que colocava o ambiente como determinante nas acções humanas.O responsável por esta corrente foi:',
    answers: ['Friedrich Ratzel', 'Vidal de la Blache', 'Emanuel Kant', 'Ptolomeu', 'Newton'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 4,
    year: 2014
  },
  {
    id: 'geografia2014uem6',
    text: 'Como se chama a galáxia mais próxima da nossa?',
    answers: ['Andrómeda', 'Sistema solar', 'Via Láctea', 'Sol', 'Planeta'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 6,
    year: 2014
  },
  {
    id: 'geografia2014uem8',
    text: 'A camada de Ozono encontra maior concentração na:',
    answers: ['Termosfera', 'Estratosfera', 'Troposfera', 'Mesopausa', 'Mesosfera'],
    correct: 1,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 8,
    year: 2014
  },
  {
    id: 'geografia2014uem9',
    text: 'A atmosfera é constituída por gases que exercem um determinado peso sobre a superfície da Terra. A pressão atmosférica média que se designa de pressão normal, corresponde a...',
    answers: ['100 mbar', '100 Cm3', '1500 mbar', '1003 Cm3 ', '1013 mbar'],
    correct: 4,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 9,
    year: 2014
  },
  {
    id: 'geografia2014uem10',
    text: 'Como se designa o instrumento utilizado para medir a Temperatura?',
    answers: ['Termómetro', 'Anemómetro', 'Anemómetro', 'Pluviómetro', 'Higrómetro'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 10,
    year: 2014
  },
  {
    id: 'geografia2014uem12',
    text: 'Na troposfera a temperatura é mais alta nos pólos (-40ºC) que no equador (-80 ºC). Este facto é devido:',
    answers: ['Ao aquecimento global', 'Às mudanças climáticas', 'Ao movimento de rotação da terra', 'À maior espessura da troposfera sobre a região equatorial', 'À grande intensidade dos fenómenos meteorológicos'],
    correct: 3,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 12,
    year: 2014
  },
  {
    id: 'geografia2014uem19',
    text: 'A distribuição das diferentes formações vegetais está relacionada com a distribuição dos diferentes tipos de clima.De acordo com o texto assinale a opção correcta para a formação vegetal Maquis.',
    answers: ['Clima Tropical desértico ', 'Clima tropical seco', 'Clima temperado Mediterrânico', 'Clima Polar', 'Clima tropical húmido'],
    correct: 2,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 19,
    year: 2014
  },
  {
    id: 'geografia2014uem20',
    text: 'O tipo de formação vegetal característico das regiões de clima polar chama-se...',
    answers: ['Pradaria', 'Maquis', 'Oásis', 'Tundra', 'Taiga'],
    correct: 3,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 20,
    year: 2014
  },
  {
    id: 'geografia2014uem21',
    text: 'A composição mineralógica do basalto é:',
    answers: ['Plagioclase associada a piroxena, hornblenda e olivina ', 'Quartzo, feldspato potássico, biotite e moscovite', 'Feldspato e mica', 'Feldspato e mica e hornblenda e olivina', 'Calcite, quartzo e feldspato'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 21,
    year: 2014
  },
  {
    id: 'geografia2014uem22',
    text: 'Podem ser apresentados como exemplos de rochas formadas por metamorfismo regional:',
    answers: ['Quatzito e Gnaisse', 'Mármore e Diorito', 'Granito e Basalto', 'Mármore e Granito', 'Gnaisse e Arenito'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 22,
    year: 2014
  },
  {
    id: 'geografia2014uem25',
    text: 'O monte mais elevado de Moçambique chama-se monte Binga e possui uma altitude de:',
    answers: ['200 metros', '2200 metros', '805 metros', '1000 metros', '2436 metros'],
    correct: 4,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 25,
    year: 2014
  },
  {
    id: 'geografia2014uem26',
    text: ' Quanto à sua distribuição, os solos podem ser divididos em três ordens: zonal, azonal e intrazonal. São exemplos de solos intrazonais os seguintes:',
    answers: ['Hidromórficos, salinos e grumussolos', 'Halomórficos e podzólicos', 'Latossolos, podzólicos, desérticos, e de tundra', 'Litossolos, regossolos, grumussolos', 'Hidromórficos, regossolos, litossolos'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 26,
    year: 2014
  },
  {
    id: 'geografia2014uem27',
    text: 'Quando os solos são mal usados pode ocorrer:',
    answers: ['A perda de fertilidade', 'O aumento da fertildade', ' O crescimento rápido das plantas', 'O aumento da matéria orgânica', 'O aumento da quantidade de nutrientes'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 27,
    year: 2014
  },
  {
    id: 'geografia2014uem28',
    text: 'A erosão é o processo de:',
    answers: ['Adubação dos solos ', 'Remoção e transporte de partículas do solo de um lugar para outro', 'Fertilização dos solos', 'Compactação dos solos', 'Deposição de partículas de solo, compactação e adubação dos solos'],
    correct: 1,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 28,
    year: 2014
  },
  {
    id: 'geografia2014uem33',
    text: 'Considera-se saldo fisiológico positivo:',
    answers: ['Quando o número de imigrantes é superior ao número de emigrantes', 'Quando o número de nascimentos é inferior ao número de mortes', 'Quando o número de nascimentos é equivalente ao número de mortes', 'Quando o número de nascimentos é superior ao número de mortes', 'Quando o número de emigrantes é superior ao número de mortes'],
    correct: 3,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 33,
    year: 2014
  },
  {
    id: 'geografia2014uem37',
    text: 'Muitos trabalhadores, devido a grande distância que se encontram de seus locais de trabalho precisam de se deslocar com um gasto de até três horas a partir de suas casas, configurando um verdadeiro processo de migração, o qual é chamado de:',
    answers: ['Migração interurbana', 'Emigração tubular', '805 metros', 'Migração sazonal', 'Transumância'],
    correct: 2,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 37,
    year: 2014
  },
  {
    id: 'geografia2014uem38',
    text: 'Muitos trabalhadores, devido a grande distância que se encontram de seus locais de trabalho precisam de se deslocar com um gasto de até três horas a partir de suas casas, configurando um verdadeiro processo de migração, o qual é chamado de:',
    answers: ['Que participa do mercado de trabalho', 'Dotada activamente de poder económico', 'Que trabalha na indústria', 'Que está empregada ', 'Que possui bens e está no mercado de consumo'],
    correct: 0,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 38,
    year: 2014
  },
  {
    id: 'geografia2014uem49',
    text: 'O ponto mais alto da Primeira Revolução Industrial foi marcado pela:',
    answers: ['Descoberta do petróleo ', 'Invenção da máquina a vapor', 'Descoberta de ferro', 'Descoberta do carvão', 'Descoberta da energia nuclear'],
    correct: 1,
    subject: 3,
    level: 11,
    institution: 0,
    nr: 49,
    year: 2014
  },
];

module.exports = geografia2014uem;